---
abstract: 'Name your accessors get_foo() and set_foo() or _set_foo().'
author:
  - 'Elliot Shank <perl@galumph.com>'
build_requires:
  Test::More: 0.72
configure_requires:
  Module::Build: 0.2808
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Accessors-ReadWritePrivate
no_index:
  directory:
    - xt
  file: []
provides:
  MooseX::Accessors::ReadWritePrivate:
    file: lib/MooseX/Accessors/ReadWritePrivate.pm
    version: v1.3.0
  MooseX::Accessors::ReadWritePrivate::Role::Attribute:
    file: lib/MooseX/Accessors/ReadWritePrivate/Role/Attribute.pm
    version: v1.3.0
requires:
  Moose: 0.84
  Moose::Exporter: 0
  Moose::Role: 0
  Moose::Util::MetaRole: 0
  strict: 0
  utf8: 0
  version: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: v1.3.0
